### ISSUE TITLE
v1.0.2 npm package doesn't include the dist folder

### ISSUE THREAD

**Issue by ycanardeau** [mrdck/nestjs-ajv-glue#3]
Thanks for publishing v1.0.2, but I've noticed that it doesn't include the dist folder. Can you please check it when you have time?

**Comment by mateuszperlak** [comment]
Finally I've found some time to address this issue and it seems like my publish didn't include any files beside package.json and README as You have mentioned.  I just published new release with distribution bundled. I just added prepack hook so next time there should not be any problems with missing files. Let me know if this works for you.

**Comment by ycanardeau** [comment]
It works perfectly for me, thanks for your support!

**Comment by mateuszperlak** [comment]
I'm glad it worked for you!
